name: ufood

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1
  dio: ^4.0.6
  sembast: ^3.3.0
  flutter_html: ^3.0.0-alpha.6
  expandable: ^5.0.1
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_svg: ^1.1.5
  loading_animation_widget: ^1.2.0+3
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.2
  connectivity_plus: ^2.3.9
  cached_network_image: ^3.2.2
  auto_route: ^5.0.2
  json_annotation: ^4.7.0
  auto_route_generator: ^5.0.3
  dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

flutter_icons:
  image_path: "assets/png/ic_launcher.png"
  android: true
  ios: true
